FROM adoptopenjdk:15-jdk-hotspot
# FROM eclipse-temurin:11-jdk

WORKDIR /app
COPY . /app

RUN mkdir -p target/classes
RUN javac --enable-preview --release 15 -d target/classes $(find src/main/java -name "*.java")

CMD ["java", "--enable-preview", "-cp", "target/classes", "com.example.Main"]
