FROM adoptopenjdk:9-jdk-hotspot
# FROM eclipse-temurin:11-jdk

WORKDIR /app
COPY . /app

RUN mkdir -p target/classes
RUN javac -d target/classes $(find src/main/java -name "*.java")

CMD ["java", "-cp", "target/classes", "com.example.Main"]
